In [1154]:
import json
import re
import numpy as np
import pandas as pd
from pandas.io.json import json_normalize

In [1155]:
data = []
with open('location.json') as json_file:
    for line in json_file:
        data.append(json.loads(line))

In [1156]:
for line in data:
    print (line)
    break

{'payload': {'existence_full': 1, 'geo_virtual': '["56.9459720|-2.1971226|20|within_50m|4"]', 'latitude': '56.945972', 'locality': 'Stonehaven', '_records_touched': '{"crawl":8,"lssi":0,"polygon_centroid":0,"geocoder":0,"user_submission":0,"tdc":0,"gov":0}', 'address': 'The Lodge, Dunottar', 'email': 'dunnottarcastle@btconnect.com', 'existence_ml': 0.5694238217658721, 'domain_aggregate': '', 'name': 'Dunnottar Castle', 'search_tags': ['Dunnottar Castle Aberdeenshire', 'Dunotter Castle'], 'admin_region': 'Scotland', 'existence': 1, 'category_labels': [['Landmarks', 'Buildings and Structures']], 'post_town': 'Stonehaven', 'region': 'Kincardineshire', 'review_count': '719', 'geocode_level': 'within_50m', 'tel': '01569 762173', 'placerank': 65, 'longitude': '-2.197123', 'placerank_ml': 37.27916073464469, 'fax': '01330 860325', 'category_ids_text_search': '', 'website': 'http://www.dunnottarcastle.co.uk', 'status': '1', 'geocode_confidence': '20', 'postcode': 'AB39 2TL', 'category_ids': [108], 'country': 'gb', '_geocode_quality': '4'}, 'uuid': '3867aaf3-12ab-434f-b12b-5d627b3359c3'}

In [1157]:
df = json_normalize(data)

In [1158]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 538 entries, 0 to 537
Data columns (total 41 columns):
payload._geocode_quality            513 non-null object
payload._records_touched            529 non-null object
payload.address                     525 non-null object
payload.address_extended            28 non-null object
payload.admin_region                529 non-null object
payload.category_ids                527 non-null object
payload.category_ids_text_search    529 non-null object
payload.category_labels             527 non-null object
payload.country                     529 non-null object
payload.domain_aggregate            529 non-null object
payload.email                       448 non-null object
payload.existence                   529 non-null float64
payload.existence_full              529 non-null float64
payload.existence_ml                529 non-null float64
payload.fax                         360 non-null object
payload.geo_virtual                 513 non-null object
payload.geocode_confidence          513 non-null object
payload.geocode_level               513 non-null object
payload.hours                       306 non-null object
payload.hours_display               306 non-null object
payload.languages                   254 non-null object
payload.latitude                    513 non-null object
payload.locality                    529 non-null object
payload.longitude                   513 non-null object
payload.name                        529 non-null object
payload.name_variants               1 non-null object
payload.neighborhood                364 non-null object
payload.placerank                   529 non-null float64
payload.placerank_ml                529 non-null float64
payload.po_box                      3 non-null object
payload.post_town                   529 non-null object
payload.postcode                    529 non-null object
payload.region                      529 non-null object
payload.review_count                529 non-null object
payload.search_tags                 498 non-null object
payload.status                      529 non-null object
payload.status_closed               24 non-null object
payload.tel                         524 non-null object
payload.website                     518 non-null object
payload.yext_id                     1 non-null object
uuid                                538 non-null object
dtypes: float64(5), object(36)
memory usage: 172.4+ KB
None

### Return every unique locality along with how often it occurs

In [1159]:
city_list = df['payload.locality'].value_counts()

In [1160]:
city_list.head()

London       149
Edinburgh     23
Glasgow       15
Liverpool     15
Oxford        13
Name: payload.locality, dtype: int64

### Return all addresses that start with a number (returning just the address)

In [1161]:
num_addresses = df['payload.address'][df['payload.address'].str.contains('^ *\d.*$', na=False)]

In [1162]:
num_addresses.sample(5)

81       174 Woodlands Rd
97             25 High St
126       5-7 Eastgate St
55            100 Grey St
157    87-135 Brompton Rd
Name: payload.address, dtype: object

### Return all rows with addresses that don't contain a number (return the entire row)

In [1163]:
non_num_records = df[df['payload.address'].str.contains('^[^0-9]+$', na=False)]

In [1164]:
non_num_records.sample(5)

,payload._geocode_quality,payload._records_touched,payload.address,payload.address_extended,payload.admin_region,payload.category_ids,payload.category_ids_text_search,payload.category_labels,payload.country,payload.domain_aggregate,...,payload.postcode,payload.region,payload.review_count,payload.search_tags,payload.status,payload.status_closed,payload.tel,payload.website,payload.yext_id,uuid
418,2,"{""crawl"":5,""lssi"":0,""polygon_centroid"":0,""geoc...",Sandwick,NaN,Scotland,[430],,[[Travel]],gb,,...,KW16 3LR,Orkney,470,[Skara Brae],1,NaN,01856 841815,http://www.historic-scotland.gov.uk/propertyre...,NaN,03fd4035-d3a2-436d-b608-402ae20260e2
486,4,"{""crawl"":10,""lssi"":0,""polygon_centroid"":0,""geo...",The Mound,NaN,Scotland,[310],,"[[Social, Arts, Art Dealers and Galleries]]",gb,,...,EH2 2EL,Lothian,390,"[Scottish National Gallery Museum, Scottish Na...",1,NaN,0131 624 6200,http://www.nationalgalleries.org,NaN,1ecb9006-25d5-4baf-8d04-f87ebd145c4f
380,4,"{""crawl"":6,""lssi"":0,""polygon_centroid"":0,""geoc...",North Holmes Rd,NaN,England,[55],,"[[Community and Government, Religious, Churches]]",gb,,...,CT1 1PW,Kent,55,NaN,1,NaN,01227 768072,http://www.martinpaul.org,NaN,337dd479-0269-4301-a824-f19669853489
281,4,"{""crawl"":16,""lssi"":0,""polygon_centroid"":0,""geo...",Fleet St,NaN,England,[55],,"[[Community and Government, Religious, Churches]]",gb,,...,EC4Y 8AU,Greater London,48,"[St. Bride's, St. Bride's London, St. Brides C...",1,1,020 7427 0133,http://www.stbrides.com,NaN,81f3dbc8-f96f-4b7d-a8b3-797cdf986caa
447,4,"{""crawl"":6,""lssi"":0,""polygon_centroid"":0,""geoc...",St Mary at Hill Eastcheap,NaN,England,[55],,"[[Community and Government, Religious, Churches]]",gb,,...,EC3R 8EE,Greater London,1,"[St Mary-at-Hill, St Mary-at-Hill Church]",1,NaN,020 7626 4184,http://www.stmary-at-hill.org,NaN,5b87e8d0-14c2-414e-b487-f0b75decdb51

### Return the number of records that are museums

In [1165]:
df['payload.category_labels'].astype(str)
df.head(1)

,payload._geocode_quality,payload._records_touched,payload.address,payload.address_extended,payload.admin_region,payload.category_ids,payload.category_ids_text_search,payload.category_labels,payload.country,payload.domain_aggregate,...,payload.postcode,payload.region,payload.review_count,payload.search_tags,payload.status,payload.status_closed,payload.tel,payload.website,payload.yext_id,uuid
0,4,"{""crawl"":8,""lssi"":0,""polygon_centroid"":0,""geoc...","The Lodge, Dunottar",NaN,Scotland,[108],,"[[Landmarks, Buildings and Structures]]",gb,,...,AB39 2TL,Kincardineshire,719,"[Dunnottar Castle Aberdeenshire, Dunotter Castle]",1,NaN,01569 762173,http://www.dunnottarcastle.co.uk,NaN,3867aaf3-12ab-434f-b12b-5d627b3359c3

In [1166]:
#Changing the category_labels into string format
df['payload.category_labels'] = df['payload.category_labels'].astype(str)

In [1167]:
#Formatting the category_labels so they are easier to query in the future
df['payload.category_labels'].str.replace('\[|\]|\'', '').head()

0        Landmarks, Buildings and Structures
1       Social, Food and Dining, Restaurants
2        Landmarks, Buildings and Structures
3                         Landmarks, Gardens
4    Landmarks, Historic and Protected Sites
Name: payload.category_labels, dtype: object

In [1168]:
#Getting the first item in the shape (rows, not including columns)
df[df['payload.category_labels'].str.contains('Museums')].shape[0]

72

### Return a new object containing uuid, name, website & email add for all rows that have values for all 4 attributes; Exclude any rows that don’t have all four

In [1169]:
basic_attributes = df[['uuid','payload.name','payload.website','payload.email']].dropna(axis=0, how='any')

In [1170]:
basic_attributes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 447 entries, 0 to 537
Data columns (total 4 columns):
uuid               447 non-null object
payload.name       447 non-null object
payload.website    447 non-null object
payload.email      447 non-null object
dtypes: object(4)
memory usage: 17.5+ KB

In [1171]:
df['monday_hours'] = df['payload.hours'].str.extract(r'monday\"\:\[(.+?(?=],"))').str.findall(r'\d+\:\d+')
df['tuesday_hours'] = df['payload.hours'].str.extract(r'tuesday\"\:\[(.+?(?=],"))').str.findall(r'\d+\:\d+')
df['wednesday_hours'] = df['payload.hours'].str.extract(r'wednesday\"\:\[(.+?(?=],"))').str.findall(r'\d+\:\d+')
df['thursday_hours'] = df['payload.hours'].str.extract(r'thursday\"\:\[(.+?(?=],"))').str.findall(r'\d+\:\d+')
df['friday_hours'] = df['payload.hours'].str.extract(r'friday\"\:\[(.+?(?=],"))').str.findall(r'\d+\:\d+')
df['saturday_hours'] = df['payload.hours'].str.extract(r'saturday\"\:\[(.+?(?=],"))').str.findall(r'\d+\:\d+')
df['sunday_hours'] = df['payload.hours'].str.extract(r'sunday\"\:\[(.+?(?=]}))').str.findall(r'\d+\:\d+')

C:\Users\musta\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  """Entry point for launching an IPython kernel.
C:\Users\musta\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

C:\Users\musta\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\musta\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  after removing the cwd from sys.path.
C:\Users\musta\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  """
C:\Users\musta\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

C:\Users\musta\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  import sys

In [1172]:
df.sample(5)

,payload._geocode_quality,payload._records_touched,payload.address,payload.address_extended,payload.admin_region,payload.category_ids,payload.category_ids_text_search,payload.category_labels,payload.country,payload.domain_aggregate,...,payload.website,payload.yext_id,uuid,monday_hours,tuesday_hours,wednesday_hours,thursday_hours,friday_hours,saturday_hours,sunday_hours
119,4,"{""crawl"":8,""lssi"":0,""polygon_centroid"":0,""geoc...",45-49 Berry St,NaN,England,[457],,"[['Social', 'Food and Dining', 'Restaurants', ...",gb,,...,http://www.archrestaurant.co.uk,NaN,1291780c-777d-4b6b-a82d-89d9aba000d5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469,4,"{""crawl"":22,""lssi"":0,""polygon_centroid"":0,""geo...","Sunken Gardens, Western Esplanade",NaN,England,[319],,"[['Social', 'Entertainment', 'Amusement Parks']]",gb,,...,http://www.adventureisland.co.uk,NaN,31e4ef66-67c2-48a1-82f1-26d16e9e305f,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,4,"{""crawl"":3,""lssi"":0,""polygon_centroid"":0,""geoc...",5 Blythswood Sq,NaN,Scotland,[299],,"[['Businesses and Services', 'Real Estate', 'C...",gb,,...,http://mackintoshhouse.co.uk,NaN,5b23adf1-0b00-440f-9e63-c25015070a53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,4,"{""crawl"":14,""lssi"":0,""polygon_centroid"":0,""geo...",1 Sir Matt Busby Way,NaN,England,[406],,"[['Sports and Recreation', 'Stadiums and Arena...",gb,,...,http://www.manutd.com,NaN,350a81ef-7db3-4fa0-b883-e1ef75d96b06,"[9:30, 17:00]","[9:30, 17:00]","[9:30, 17:00]","[9:30, 17:00]","[9:30, 17:00]","[9:30, 17:00]","[9:30, 17:00]"
490,4,"{""crawl"":3,""lssi"":0,""polygon_centroid"":0,""geoc...",The Registry,NaN,England,[29],,"[['Community and Government', 'Education', 'Co...",gb,,...,http://www.kent.ac.uk/locations/canterbury,NaN,1c09092e-c241-44de-b742-79550ca9fbdb,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Return all rows, but transform the names to all lower case while changing nothing else

In [1173]:
dflowername = df.copy()

In [1174]:
dflowername['payload.name'] = df1['payload.name'].str.lower()

In [1175]:
dflowername.sample(1)

,payload._geocode_quality,payload._records_touched,payload.address,payload.address_extended,payload.admin_region,payload.category_ids,payload.category_ids_text_search,payload.category_labels,payload.country,payload.domain_aggregate,...,payload.website,payload.yext_id,uuid,monday_hours,tuesday_hours,wednesday_hours,thursday_hours,friday_hours,saturday_hours,sunday_hours
109,4,"{""crawl"":3,""lssi"":0,""polygon_centroid"":0,""geoc...",36 St Andrew Sq,NaN,Scotland,[108],,"[['Landmarks', 'Buildings and Structures']]",gb,,...,NaN,NaN,217a7f58-058a-44db-8355-2cdc679bd824,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1176]:
dflowername['payload.name'].sample(5)

285                                  stamford bridge
139                        st james's hotel and club
501                                  tower of london
138    hampton by hilton liverpool city centre hotel
312                                     castle hotel
Name: payload.name, dtype: object

### Return all rows for businesses that open before 10:00 a.m. on Sundays

In [1177]:
#df2['sunday_hours'] = pd.to_datetime(df2['sunday_hours'], format='%H:%M', errors = 'ignore')

In [1178]:
#Extracting all the rows where sunday hours are before 10
sunbefore10 = df['payload.hours'].str.extract('sunday\"\:\[\[\"([0-9])\:')
sunbefore10.dropna(axis=0, inplace=True)

C:\Users\musta\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

In [1179]:
sunday = df.iloc[sunbefore10.index].reset_index(drop=True)

In [1180]:
sunday.sample(5)

,payload._geocode_quality,payload._records_touched,payload.address,payload.address_extended,payload.admin_region,payload.category_ids,payload.category_ids_text_search,payload.category_labels,payload.country,payload.domain_aggregate,...,payload.website,payload.yext_id,uuid,monday_hours,tuesday_hours,wednesday_hours,thursday_hours,friday_hours,saturday_hours,sunday_hours
18,4,"{""crawl"":13,""lssi"":0,""polygon_centroid"":0,""geo...",Castle Esplanade,NaN,Scotland,[108],,"[['Landmarks', 'Buildings and Structures']]",gb,,...,http://www.stirlingcastle.gov.uk,NaN,1b3dd6d6-ed22-4b2c-bbd1-772bfdfdd174,"[9:30, 17:00]","[9:30, 17:00]","[9:30, 17:00]","[9:30, 17:00]","[9:30, 17:00]","[9:30, 17:00]","[9:30, 17:00]"
14,2,"{""crawl"":12,""lssi"":0,""polygon_centroid"":0,""geo...",Bigbury-on-Sea,NaN,England,[436],,"[['Travel', 'Lodging', 'Hotels and Motels']]",gb,,...,http://www.burghisland.com,NaN,e6a62e4d-87f7-4640-9944-4ac42a0c0074,"[7:00, 22:00]","[7:00, 22:00]","[7:00, 22:00]","[7:00, 22:00]","[7:00, 22:00]","[7:00, 22:00]","[7:00, 22:00]"
42,4,"{""crawl"":16,""lssi"":0,""polygon_centroid"":0,""geo...",St James' Mount,NaN,England,[55],,"[['Community and Government', 'Religious', 'Ch...",gb,,...,http://www.liverpoolcathedral.org.uk,NaN,e2a1009a-7a9b-45aa-b149-61e82cc1f186,"[8:00, 18:00]","[8:00, 18:00]","[8:00, 18:00]","[8:00, 18:00]","[8:00, 18:00]","[8:00, 18:00]","[8:00, 18:00]"
8,4,"{""crawl"":26,""lssi"":0,""polygon_centroid"":0,""geo...",174 Woodlands Rd,NaN,England,[436],,"[['Travel', 'Lodging', 'Hotels and Motels']]",gb,,...,http://www.hotelterravina.co.uk,NaN,3a60e14c-ee29-454a-a805-c648bd08f2c3,"[7:00, 21:45]","[7:00, 21:45]","[7:00, 21:45]","[7:00, 21:45]","[7:00, 21:45]","[7:00, 21:45]","[7:00, 21:45]"
33,4,"{""crawl"":5,""lssi"":0,""polygon_centroid"":0,""geoc...",Main Rd,NaN,England,[425],,"[['Transportation', 'Transport Hubs', 'Airport...",gb,,...,http://www.bigginhillairport.com,NaN,8f3f4a35-4e00-4b21-829d-29606a1b0585,"[7:30, 21:00]","[7:30, 21:00]","[7:30, 21:00]","[7:30, 21:00]","[7:30, 21:00]","[9:00, 20:00]","[9:00, 20:00]"